const a = {
  "新增": "Add",
  "编辑": "Edit",
  "删除": "Delete",
  "查看": "Check",
  "启用": "Enable",
  "禁用": "Disabled",
  "保存": "Save",
  "取消": "Cancel",
  "确定": "Confirm",
  "重置": "Reset",
  "搜索": "search",
  "新增API": "Add API",
  "编辑API": "Edit API",
  "删除API": "Delete API",
  "验证授权": "Verify authorization",
  "角色用户": "Role Users",
  "权限设置": "Permission settings",
  "导入": "Import",
  "解锁": "Unlock",
  "修改密码": "Change password",
  "切换客户": "Switching Customers",
  "移除用户": "Remove User ",
  "添加用户": "Add user",
  "生成授权": "Generate Authorization",
  "授权范围-功能范围设置": "Authorization Scope - Functional Scope Setting",
  "授权范围-数据范围设置": "Authorization Scope - Data Range Setting",
  "授权范围-部门范围设置": "Authorization Scope - Department Scope Setting",
  "使用权限-功能权限设置": "Usage permissions - Function permission settings",
  "使用权限-数据权限设置": "Usage permissions - Data permission settings",
  "操作": "Operation",
  "更多": "More",
  "删除用户": "Delete User",
  "禁用用户": "Disable User",
  "启用用户": "Enable User",
  "终端用户轨迹": "User Trace",
  "确认": "Confirm",
  "批量导入": "Batch Import",
  "导出全部": "Export All",
  "下载导入模板": "Download Import Template",
  "查询": "Query",
  "创建任务": "Create Task",
  "开始任务": "Start Task",
  "暂停任务": "Paused Task",
  "取消任务": "Cancel Task",
  "上传": "Upload",
  "提交": "Submit",
  "添加选中": "Add selected",
  "删除选中": "Delete selected",
  "下一步：基准站选择": "Next: sites selection",
  "上一步：任务信息": "Previous: task info",
  "下一步：确认任务": "Next: confirm task",
  "上一步：基准站选择": "Previous: site selection",
  "返回基准站任务": "Return to site task",
  "下载": "Download",
  "批量修改": "Batch Modify",
  "绑定": "Binding",
  "解绑": "Unbinding",
  "确定解绑": "Confirm Unbinding",
  "高级搜索": "Senior Search",
  "修改": "Modify",
  "更新授权": "Update Authorization",
  "立即开通": "Activate Now",
  "进入系统主页": "Enter the system homepage",
  "删除账号": "Delete Account",
  "禁用账号": "DisableAccount",
  "启用账号": "Enable Account",
  "删除全部": "Delete All",
  "下一步：数据流选择": "Next: streams selection",
  "上一步：数据流选择": "Previous: streams selection",
  "导出": "Export",
  "下载文件": "Download File",
  "关闭": "Close",
  "断开": "Break",
  "重新登录": "Login Again",
  "返回上一级": "Go Back",
  "全部文件": "All files",
  "打开": "Open"
}
module.exports = a