const test = {
  Save: 'Save',
  Modify: 'Modify',
  Cancel: 'Cancel',
  Confirm: 'Confirm',
  UpdateAuthorization: 'Update Authorization',
  ActivateNow: 'Activate Now',
  Sure: 'Sure',
  EnterSystemHomepage: 'Enter the system homepage',
  Operation: 'Operation',
  View: 'View',
  Edit: 'Edit',
  Delete: 'Delete',
  More: 'More',
  DeleteAccount: 'Delete Account',
  DisableAccount: 'Disable Account',
  EnableAccount: 'Enable Account',
  ChangePassword: 'Change Password',
  ClientTrajectory: 'User Trace',
  Cancel: 'Cancel',
  Confirm: 'Confirm',
  Add: 'Add',
  BatchImport: 'Batch Import',
  BatchExport: 'Export All',
  TemplateDownload: 'Download Import Template',
  Query: 'Query',
  Save: 'Save',
  CreateTask: 'Create Task',
  StartTask: 'Start Task',
  PausedTask: 'Paused Task',
  CancelTask: 'Cancel Task',
  DeleteAll: 'Delete All',
  NextSiteSelection: 'Next: streams selection',
  PreviousTaskInfo: 'Previous: task info',
  NextConfirmTask: 'Next: confirm task',
  PreviousSiteSelection: 'Previous: streams selection',
  Export: 'Export',
  DownloadFile: 'Download File',
  Disable: 'Disable',
  Enable: 'Enable',
  Reset: 'Reset',
  SeniorSearch: 'Senior Search',
  Close: 'Close',
  Break: 'Break',
  BatchModify: 'Batch Modify',
  ConfirmUnbinding: 'Confirm Unbinding',
  Save: 'Save',
  Modify: 'Modify',
  Cancel: 'Cancel',
  Confirm: 'Confirm',
  UpdateAuthorization: 'Update Authorization',
  ActivateNow: 'Activate Now',
  Sure: 'Sure',
  EnterSystemHomepage: 'Enter the system homepage',
  Save: 'Save',
  Modify: 'Modify',
  Cancel: 'Cancel',
  Confirm: 'Confirm',
  SignInAgain: 'Login Again',
  Operation: 'Operation',
  View: 'View',
  Edit: 'Edit',
  Delete: 'Delete',
  More: 'More',
  DeleteAccount: 'Delete Account',
  DisableAccount: 'DisableAccount',
  EnableAccount: 'Enable Account',
  Cancel: 'Cancel',
  Save: 'Save',
  StartTask: 'Start task',
  PausedTask: 'Paused task',
  Disable: 'Disable',
  Enable: 'Enable',
  Reset: 'Reset',
  Operation: 'Operation',
  Cancel: 'Cancel',
  Edit: 'Edit',
  Enable: 'Enable',
  Disable: 'Disable',
  Delete: 'Delete',
  CreateTask: 'Create task',
  Query: 'Query',
  GoBack: 'Go Back',
  AllFiles: 'All files',
  SeniorSearch: 'Senior Search',
  Reset: 'Reset',
  Close: 'Close',
  Open: 'Open'

}

module.exports = test